config:
  gcp:project: vici-app-prod
  gcp:region: us-central1
  vici-infra:env: prod
  vici-infra:cluster_name: vici-prod
  vici-infra:registry_name: vici-images
  vici-infra:app_hostname: usevici.com
  vici-infra:github_org: ahcarpenter
encryptionsalt: v1:gPuz2z50nzI=:v1:2gLvT1VXroTE6tCy:XFo5BiqJPiNSPUgnpI1y14ilSf1WlQ==
