config:
  gcp:project: vici-app-dev
  gcp:region: us-central1
  vici-infra:env: dev
  vici-infra:cluster_name: vici-dev
  vici-infra:registry_name: vici-images
  vici-infra:app_hostname: dev.usevici.com
  vici-infra:github_org: ahcarpenter
  vici-infra:temporal_db_user:
    secure: v1:ze0QmT22r7B8mq/n:+pU+GNlO85WrSSIIN1a+xs5U0kE=
  vici-infra:temporal_db_password:
    secure: v1:d/0yncKnfYAVdkaD:stCzZtUJLO5W37qzWwU5rfyWLfE=
encryptionsalt: v1:EeaM9dDANHQ=:v1:5ITYxT6i+0l5K9L4:bR/RYlqgH83b9l6EaB+4B1tXsOwUKw==
