config:
  gcp:project: vici-app-dev
  gcp:region: us-central1
  vici-infra:env: dev
  vici-infra:cluster_name: vici-dev
  vici-infra:registry_name: vici-images
  vici-infra:app_hostname: dev.usevici.com
  vici-infra:github_org: ahcarpenter
encryptionsalt: v1:81TxmqrpLik=:v1:Dp1mky8HdWfv+Qpy:qJCnVkuGWB6AtDz4AcFjdaAT3HjSqA==
