config:
  gcp:project: vici-app-dev
  gcp:region: us-central1
  vici-infra:env: dev
  vici-infra:cluster_name: vici-dev
  vici-infra:registry_name: vici-images
  vici-infra:app_hostname: dev.usevici.com
  vici-infra:github_org: ahcarpenter
  vici-infra:temporal_db_user:
    secure: v1:tIr5x37jsfD9KrV1:lERgurpFhOLoKePqYeJf2bi0gn5S1lYH
  vici-infra:temporal_db_password:
    secure: v1:RSPtynFKg5YZNqs5:YG+cL1tr0dmZ7vptxgRsukzAAYTKS+ucSGJ3Xi6jkPKw+Ae8d8FJXAKOrnVqVXQh3nHPHIROZMYdlp4=
encryptionsalt: v1:eQAsOykhiHk=:v1:ePoMuTEO8Qjl/OSL:1CRWsrB0kPHDXvCOt9xrBm80+a2EQQ==
