config:
  gcp:project: vici-app-staging
  gcp:region: us-central1
  vici-infra:env: staging
  vici-infra:cluster_name: vici-staging
  vici-infra:registry_name: vici-images
  vici-infra:app_hostname: staging.usevici.com
  vici-infra:github_org: ahcarpenter
encryptionsalt: v1:sZ/V8RlazvM=:v1:PeCCcVywxm2lfDd4:oxrp74NRAxLl2JZ1V5SiX7mSlfcLIA==
