# Source: https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-query.yaml
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [nop]
      processors: [batch]
      exporters: [nop]
  telemetry:
    resource:
      service.name: jaeger-query
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: main_storage

  jaeger_storage:
    backends:
      main_storage:
        opensearch:
          server_urls:
            - http://opensearch:9200
          indices:
            index_prefix: "jaeger-main"
            spans:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 1
              replicas: 0

receivers:
  nop:

processors:
  batch:

exporters:
  nop:
