{
 "title": "1 Kubernetes All-in-one Cluster Monitoring KR(v1.26.0)",
 "description": "This dashboard is the education purpose for the Grafana panel and other functions. Thus it cannot be guaranteed for other environment. ",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   { "name": "duration", "query": "2m,5m,10m,30m,1h" },
   {
    "name": "instance",
    "query": {
     "query": "query_result(node_uname_info{nodename=\"$node\"})"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},  pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "클러스터 요약",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "마스터 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "노드 현황",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "label_replace(up{job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")"
    },
    {
     "expr": "label_replace(avg by (kubernetes_node) (time() - node_boot_time_seconds), \"node\", \"$1\", \"kubernetes_node\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "네임스페이스",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": " count(kube_pod_info)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "전체 클러스터",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "노드별 CPU 점유율",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance,nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[$duration])) + on(instance) group_left(nodename) \nnode_uname_info) - 1",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "노드별 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(node_network_receive_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(in)"
    },
    {
     "expr": "sum (rate(node_network_transmit_bytes_total[$duration]))",
     "legendFormat": "{{kubernetes_node}}(out)"
    }
   ]
  },
  {
   "title": "API 서버 호출",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[$duration]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "노드 $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU 점유율",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", node=\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "메모리 점유율",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{node=\"$node\"}-node_memory_MemAvailable_bytes{node=\"$node\"})/node_memory_MemTotal_bytes{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "디스크 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node=\"$node\"} - node_filesystem_avail_bytes{node=\"$node\"}) by (node) / sum(node_filesystem_size_bytes{node=\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "CPU 코어",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "File descriptor / Context switches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk IOPS 완료",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$duration])",
     "legendFormat": "{{device}}_Writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "메모리",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\",node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Pod $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod 생성시간",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time()-kube_pod_start_time{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod 가동 상태",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{pod=\"$pod\", reason!~\"ContainerCreating\"})"
    }
   ]
  },
  {
   "title": "10분 이내 재시작",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(kube_pod_container_status_restarts_total{pod=\"$pod\"}[10m])))"
    }
   ]
  },
  {
   "title": "리소스 사용량",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "CPU(%)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory(bytes)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=\"$pod\"}) # not working on containerD now",
     "legendFormat": "File system usage"
    }
   ]
  },
  {
   "title": "리소스 할당  제한",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\"})",
     "legendFormat": "CPU core"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$duration]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "메모리 상태(Swap/Failure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{pod=\"$pod\"}) by (pod)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{pod=\"$pod\"}[$duration])) by (pod)",
     "legendFormat": "Memory Failure"
    }
   ]
  },
  {
   "title": "스레드 개수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_threads{pod=\"$pod\", container!=\"POD\"})",
     "legendFormat": "Thread"
    }
   ]
  }
 ]
}