name: CD Dev

"on":
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    uses: ./.github/workflows/cd-base.yml
    with:
      stack: dev
      command: up
      gcp_project: vici-app-dev
    secrets:
      WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.GCP_CI_SA_EMAIL }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
